# Introdução ao NumPy - Primeiros passos na biblioteca

### Criando matrizes:

In [27]:
import numpy as np

a = np.array([1, 2, 3]) # array de uma dimensão.
print(a)

[1 2 3]


In [28]:
b = np.array([(2, 3, 4), (5, 6, 7), (8, 9, 1)])  # array de múltiplas dimensões.
print(b)

[[2 3 4]
 [5 6 7]
 [8 9 1]]


In [29]:
c = np.zeros((4, 3)) # a função "zeros" imprime uma matriz de 4 por 3.
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [30]:
d = np.ones((3, 4)) # a função "ones" imprime uma matriz de 3 por 4.
print(d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [31]:
e = np.eye(4) # a função eye cria uma matriz cuja diagonal principal é de 1 enquanto o restante 0.
print(e0

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Aplicando funções nas minhas variáveis:

##### Usando a variável b de exemplo

In [34]:
b.max() # função que mostra o maior elemento da matriz.

9

In [37]:
b.min() # função que mostra o menor elemento da matriz.

1

In [40]:
b.sum() # função que soma todos os elementos da matriz.

45

In [41]:
b.mean() # função que calcula a média.

5.0

In [43]:
b.std() # função que calcula o desvio padrão.

2.581988897471611

obs.: sei que esses nomes de variáveis não seguem as boas práticas, no entanto, é apenas em caráter de aprendizado considerando a praticidade.